name: Generate Snake

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

  # Run manually from the Actions tab
  workflow_dispatch:

  pull_request:
    branches:
      - main


permissions:
  contents: write  # allow pushing changes to the repo

jobs:
  build:
    name: Generate GitHub Contribution Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensures we can commit to existing branch

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Move generated files into output folder
        run: |
          mkdir -p output
          mv dist/* output/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "update snake animation" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
